### ISSUE TITLE
Invalid Profile

### ISSUE THREAD

**Issue by barryhaertel** [poundbangbash/community-screenrecording-pppc-profile#22]
Commit 674b75d792aced749f007aa9380b4638f9274536 (latest 2 days ago) shows up as an invalid profile, PPPC Utility will not load it, nor Kandji MDM

**Comment by poundbangbash** [comment]
Thanks for the submission. Looks like it was commit https://github.com/poundbangbash/community-screenrecording-pppc-profile/commit/f8a1ad216bc25fdb99d8206483be2a51152c3408 that had some errant data in the CodeRequirement key.

I've fixed it and verified the payload delivers fine via SimpleMDM now where it failed before.
