### ISSUE TITLE
not working under macOS12

### ISSUE THREAD

**Issue by viderehh** [poundbangbash/community-screenrecording-pppc-profile#30]
at first, thank you for the great work
we have problems that the changes do not work under macOS12. Under macOS11 it works as desired.
Are there additional steps to do under macOS12 that we are overlooking?
MDM_ Filewave

Cheers

**Comment by poundbangbash** [comment]
There are no changes to the underlying implementation of the PPPC payloads from Big Sur to Monterey.
I recommend reaching out to FileWave support if you're seeing new behaviors.
